[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 10000
via_ir = true
bytecode_hash = "none"
cbor_metadata = false

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true
orderLiterals = true
deduplicate = true
cse = true
constantOptimizer = true
yul = true
stackAllocation = true
optimizerSteps = "dhfoDgvulfnTUtnIf[xa[r]EscLMcCTUtTOntnfDIulLculVcul[j]Tpeulxa[rul]xa[r]cLgvifCTUca[r]LSsTFOtfDnca[r]Iulc]jmul[jul]VcTOcul jmul:fDnTOcmu"

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/Px3T_Ig4x84jGwow8KpaD_UBtM5M-7Ey"
shibarium_puppynet = "https://puppynet.shibrpc.com"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/VmvZCtX4lWs4C7E8_FaPDKgMxiqqzXoN"

[etherscan]
sepolia = { key = "R6RVKKZHA5P19P4HJB6G5QPPDQ4VUERKEZ" }